config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root "albums#index"

  resources :albums do
    post 'add_artist', on: :member
    post 'remove_artist', on: :member
    resources :artists
  end

  get "/artists", to: "artists#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :artist

  validates :name, presence: true, length: { minimum: 3 }
  validates :year, numericality: { only_integer: true }, presence: true, inclusion: 1900..Date.current.year
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :album
end

app/models/user.rb
class User < ApplicationRecord
  has_many :albums
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :is_admin?, only: [:destroy]
  before_action :authenticate_user!, except: [:index]
  def index
    if user_signed_in?
      @albums = Album.where(user_id: current_user.id)
    else
      redirect_to new_user_session_path
    end
  end

  def show
    artists_service = ArtistsService.new
    all_artists = artists_service.get_all_artists
    @album = Album.find(params[:id])
    @album_artists = all_artists.select { |artist| @album.artists_ids.include?(artist['id']) }
    @artists = all_artists.reject { |artist| @album.artists_ids.include?(artist['id']) }
  end

  def new
    @album = Album.new
  end

  def remove_artist
    @album = Album.find(params[:id])

    artist_id = params[:artist_id]
    @album.artists_ids.delete(artist_id.to_i)

    if @album.save
      redirect_to @album, notice: "Artist removed successfully!"
    else
      redirect_to @album, notice: "Something went wrong! Try again later."
    end
  end

  def add_artist
    @album = Album.find(params[:id])
    artist_id = params[:artist_id]
    @album.artists_ids << artist_id unless @album.artists_ids.include?(artist_id)

    if @album.save
      redirect_to @album, notice: "Artist added successfully!"
    else
      redirect_to @album, notice: "Something went wrong! Try again later."
    end
  end

  def create
    @user = User.find(current_user.id)
    @album = Album.new(album_params)
    @album.user_id = @user.id
    if @album.save
      redirect_to @album
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to @album
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def album_params
    params.require(:album).permit(:name, :year)
  end

  def is_admin?
    unless current_user != nil && current_user.admin
      redirect_to new_user_session_path, notice: "Only admins can access this page."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname, :admin])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :admin])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/albums/_form.html.erb
<%= form_with model: album do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% album.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :year %><br>
    <%= form.number_field :year %>
    <% album.errors.full_messages_for(:year).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit class:"btn-primary mt-2"%>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render "form", album: @album %>

app/views/albums/index.html.erb
<div class="flex items-start flex-wrap justify-around w-full">
  <div class="flex flex-col justify-between gap-3 max-w-2xl">
    <h1 class="font-bold text-4xl">Albums</h1>
    <ul>
      <% @albums.each do |album| %>
        <li>
          <%= link_to album.name, album %>
        </li>
      <% end %>
    </ul>
  </div>
    <%= link_to "New Album", new_album_path, class:"btn-secondary" %>
</div>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= form_with model: @album do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @album.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :year %><br>
    <%= form.number_field :year %>
    <% @album.errors.full_messages_for(:year).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/show.html.erb
<div class="flex justify-between">
  <h1 class="text-xl font-bold pb-2"><%= "#{@album.name}, #{@album.year}" %></h1>
  <div>
    <%= link_to "Edit", edit_album_path(@album) %>
    <%= link_to "Delete Album", album_path(@album), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
  </div>
</div>

<div class="flex flex-wrap justify-start gap-3">
  <% @album_artists.each do |artist| %>
    <div class="flex flex-col justify-between rounded-lg bg-cyan-900 p-3 w-32 h-36 text-surface shadow-secondary-1 dark:bg-surface-dark dark:text-white">
      <div class="flex-col">
        <h2 class="mb-2 text-lg font-medium leading-tight"><%= artist['name'] %></h2>
        <p class="mb-4 text-sm"><%= artist['twitter'] %></p>
      </div>
      <%= button_to "Remove", remove_artist_album_path(@album, artist_id: artist['id']), method: :post, class:"btn-secondary danger" %>
    </div>
  <% end %>
</div>

<h2>Add Artsits</h2>

<div class="flex flex-wrap justify-start gap-3">
  <% @artists.each do |artist| %>
    <div class="flex flex-col justify-between rounded-lg bg-cyan-900 p-3 w-32 h-36 text-surface shadow-secondary-1 dark:bg-surface-dark dark:text-white">
      <div class="flex-col">
        <h2 class="mb-2 text-lg font-medium leading-tight"><%= artist['name'] %></h2>
        <p class="mb-4 text-sm"><%= artist['twitter'] %></p>
      </div>
      <%= button_to "Add", add_artist_album_path(@album, artist_id: artist['id'], name: artist['name'], twitter:artist['twitter']), method: :post, class:"btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/artists/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Artists</h1>
  <ul>
    <% @artists.each do |artist| %>
      <li>
        <%= "ID: #{artist["id"]} Name: #{artist["name"]}" %>
      </li>
    <% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Albums Collection" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="p-3">
      <div class="flex justify-between">
        <div>
          <%= link_to "Home", root_path, class:"text-2xl font-extrabold" %>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
        <div class="flex gap-2">
          <% if user_signed_in? %>
            <button class="btn-primary">
              <%= link_to "Profile", edit_user_registration_path %>
            </button>
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class:"btn-primary" %>
          <% else %>      
            <button class="btn-primary">
              <%= link_to "Login", new_user_session_path %>
            </button>
            <button class="btn-primary">
              <%= link_to "Signup", new_user_registration_path %>
            </button>
          <% end %>
        </div>
      </div>
      <main class="flex flex-wrap flex-col content-center mx-auto mt-6 px-5">      
      <%= yield %>
    </main>
  </body>
</html>